/** Modern resume layouts: Resume1–16. Re-exported for use in ResumeView and elsewhere. */
export { default as Resume1Layout } from "./Resume1Layout";
export { default as Resume2Layout } from "./Resume2Layout";
export { default as Resume3Layout } from "./Resume3Layout";
export { default as Resume4Layout } from "./Resume4Layout";
export { default as Resume5Layout } from "./Resume5Layout";
export { default as Resume6Layout } from "./Resume6Layout";
export { default as Resume7Layout } from "./Resume7Layout";
export { default as Resume8Layout } from "./Resume8Layout";
export { default as Resume9Layout } from "./Resume9Layout";
export { default as Resume10Layout } from "./Resume10Layout";
export { default as Resume11Layout } from "./Resume11Layout";
export { default as Resume12Layout } from "./Resume12Layout";
export { default as Resume13Layout } from "./Resume13Layout";
export { default as Resume14Layout } from "./Resume14Layout";
export { default as Resume15Layout } from "./Resume15Layout";
export { default as Resume16Layout } from "./Resume16Layout";
export { default as Resume17Layout } from "./Resume17Layout";
export { default as Resume18Layout } from "./Resume18Layout";
