name: Intervexa™ CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug Files
      run: ls -R

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # ---------- FRONTEND ----------
    - name: Install Frontend
      working-directory: Frontend
      run: npm install

    - name: Build Frontend
      working-directory: Frontend
      run: npm run build

    # ---------- BACKEND ----------
    - name: Install Backend
      working-directory: Backend
      run: npm install

    - name: Run Backend
      working-directory: Backend
      run: node -e "console.log('Backend OK')"

